# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - api-birdtracker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://birdtrackercontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_24b59872b03348cfa8d9cefb40e68c0b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0049c944228c4facaee8aedfd8c41f80 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: birdtrackercontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_24b59872b03348cfa8d9cefb40e68c0b }}/birdtrackerbackend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'api-birdtracker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_46f7abc71f544a238847f892f1d43ae3 }}
        images: 'birdtrackercontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_24b59872b03348cfa8d9cefb40e68c0b }}/birdtrackerbackend:${{ github.sha }}'